quietly set ACTELLIBNAME proasic3
quietly set PROJECT_DIR "C:/Users/dell/Desktop/WorkFolder/2D_NMR_EC_FPGA_150131"

if {[file exists presynth/_info]} {
   echo "INFO: Simulation library presynth already exists"
} else {
   vlib presynth
}
vmap presynth presynth
vmap proasic3 "D:/Actel/Libero_v9.1/Designer/lib/modelsim/precompiled/vlog/proasic3"

vlog -work presynth "${PROJECT_DIR}/hdl/n_pluse_acq.v"
vlog -work presynth "${PROJECT_DIR}/hdl/plusestate.v"
vlog -work presynth "${PROJECT_DIR}/hdl/dds_change.v"
vlog -work presynth "${PROJECT_DIR}/hdl/qq_state.v"
vlog -work presynth "${PROJECT_DIR}/hdl/qq_coder.v"
vlog -work presynth "${PROJECT_DIR}/hdl/bri_timer.v"
vlog -work presynth "${PROJECT_DIR}/hdl/bri_coder.v"
vlog -work presynth "${PROJECT_DIR}/hdl/qq_timer.v"
vlog -work presynth "${PROJECT_DIR}/hdl/bri_state.v"
vlog -work presynth "${PROJECT_DIR}/hdl/para_load.v"
vlog -work presynth "${PROJECT_DIR}/component/work/PLUSE/PLUSE.v"
vlog -work presynth "${PROJECT_DIR}/hdl/dds_timer.v"
vlog -work presynth "${PROJECT_DIR}/hdl/dds_state.v"
vlog -work presynth "${PROJECT_DIR}/hdl/dds_coder.v"
vlog -work presynth "${PROJECT_DIR}/component/work/DDS/DDS.v"
vlog -work presynth "${PROJECT_DIR}/hdl/top_code.v"
vlog -work presynth "${PROJECT_DIR}/hdl/nsctrl_choice.v"
vlog -work presynth "${PROJECT_DIR}/hdl/1ms_dump_choice.v"
vlog -work presynth "${PROJECT_DIR}/hdl/off_on_state.v"
vlog -work presynth "${PROJECT_DIR}/hdl/off_on_coder.v"
vlog -work presynth "${PROJECT_DIR}/hdl/off_on_timer.v"
vlog -work presynth "${PROJECT_DIR}/component/work/DUMP_OFF/DUMP_OFF.v"
vlog -work presynth "${PROJECT_DIR}/hdl/sd_acq_coder.v"
vlog -work presynth "${PROJECT_DIR}/hdl/sd_acq_state.v"
vlog -work presynth "${PROJECT_DIR}/smartgen/sd_sacq_inc/sd_sacq_inc.v"
vlog -work presynth "${PROJECT_DIR}/hdl/sd_acq_timer.v"
vlog -work presynth "${PROJECT_DIR}/component/work/sd_acq_top/sd_acq_top.v"
vlog -work presynth "${PROJECT_DIR}/smartgen/Timer_Cmp/Timer_Cmp.v"
vlog -work presynth "${PROJECT_DIR}/hdl/timer.v"
vlog -work presynth "${PROJECT_DIR}/hdl/state_switch.v"
vlog -work presynth "${PROJECT_DIR}/component/work/timer_top/timer_top.v"
vlog -work presynth "${PROJECT_DIR}/smartgen/cmp_constant_4b/cmp_constant_4b.v"
vlog -work presynth "${PROJECT_DIR}/hdl/dump_sustain_timer.v"
vlog -work presynth "${PROJECT_DIR}/component/work/DSTimer/DSTimer.v"
vlog -work presynth "${PROJECT_DIR}/hdl/bri_dump_sw.v"
vlog -work presynth "${PROJECT_DIR}/hdl/scan_scale_sw.v"
vlog -work presynth "${PROJECT_DIR}/hdl/s_acq_change.v"
vlog -work presynth "${PROJECT_DIR}/hdl/scanstate.v"
vlog -work presynth "${PROJECT_DIR}/hdl/state_1ms.v"
vlog -work presynth "${PROJECT_DIR}/hdl/noisestate.v"
vlog -work presynth "${PROJECT_DIR}/hdl/bridge_div.v"
vlog -work presynth "${PROJECT_DIR}/hdl/pd_pluse_coder.v"
vlog -work presynth "${PROJECT_DIR}/hdl/pd_pluse_state.v"
vlog -work presynth "${PROJECT_DIR}/smartgen/pd_pluse_inc/pd_pluse_inc.v"
vlog -work presynth "${PROJECT_DIR}/hdl/pd_pluse_timer.v"
vlog -work presynth "${PROJECT_DIR}/component/work/pd_pluse_top/pd_pluse_top.v"
vlog -work presynth "${PROJECT_DIR}/component/work/DUMP_ON/DUMP_ON.v"
vlog -work presynth "${PROJECT_DIR}/hdl/cal_load.v"
vlog -work presynth "${PROJECT_DIR}/hdl/cal_div.v"
vlog -work presynth "${PROJECT_DIR}/component/work/CAL/CAL.v"
vlog -work presynth "${PROJECT_DIR}/hdl/topctrlchange.v"
vlog -work presynth "${PROJECT_DIR}/hdl/dump_state.v"
vlog -work presynth "${PROJECT_DIR}/hdl/dump_coder.v"
vlog -work presynth "${PROJECT_DIR}/hdl/dump_timer.v"
vlog -work presynth "${PROJECT_DIR}/component/work/DUMP/DUMP.v"
vlog -work presynth "${PROJECT_DIR}/hdl/long_timer.v"
vlog -work presynth "${PROJECT_DIR}/hdl/clk_div500.v"
vlog -work presynth "${PROJECT_DIR}/smartgen/pllclk/pllclk.v"
vlog -work presynth "${PROJECT_DIR}/hdl/clk_10k.v"
vlog -work presynth "${PROJECT_DIR}/component/work/ClockManagement/ClockManagement.v"
vlog -work presynth "${PROJECT_DIR}/hdl/add_reg.v"
vlog -work presynth "${PROJECT_DIR}/hdl/s_clk_div.v"
vlog -work presynth "${PROJECT_DIR}/hdl/signalclkctrl.v"
vlog -work presynth "${PROJECT_DIR}/hdl/readata_choice.v"
vlog -work presynth "${PROJECT_DIR}/hdl/ctrl_addr.v"
vlog -work presynth "${PROJECT_DIR}/hdl/ten_choice_one.v"
vlog -work presynth "${PROJECT_DIR}/component/work/signal_acq/signal_acq.v"
vlog -work presynth "${PROJECT_DIR}/hdl/n_rdclk_syn.v"
vlog -work presynth "${PROJECT_DIR}/hdl/noise_addr.v"
vlog -work presynth "${PROJECT_DIR}/hdl/noiseclk.v"
vlog -work presynth "${PROJECT_DIR}/hdl/noiseclkctrl.v"
vlog -work presynth "${PROJECT_DIR}/smartgen/RAM/RAM.v"
vlog -work presynth "${PROJECT_DIR}/hdl/link.v"
vlog -work presynth "${PROJECT_DIR}/component/work/noise_acq/noise_acq.v"
vlog -work presynth "${PROJECT_DIR}/hdl/n_s_change.v"
vlog -work presynth "${PROJECT_DIR}/component/work/Signal_Noise_Acq/Signal_Noise_Acq.v"
vlog -work presynth "${PROJECT_DIR}/smartgen/necount_inc/necount_inc.v"
vlog -work presynth "${PROJECT_DIR}/smartgen/necount_cmp/necount_cmp.v"
vlog -work presynth "${PROJECT_DIR}/hdl/scalestate.v"
vlog -work presynth "${PROJECT_DIR}/hdl/xwe_xzcs2_syn.v"
vlog -work presynth "${PROJECT_DIR}/hdl/tri_state.v"
vlog -work presynth "${PROJECT_DIR}/hdl/reset_module.v"
vlog -work presynth "${PROJECT_DIR}/component/work/GPMI/GPMI.v"
vlog -work presynth "${PROJECT_DIR}/component/work/NMR_TOP/NMR_TOP.v"
vlog "+incdir+${PROJECT_DIR}/stimulus" -work presynth "${PROJECT_DIR}/stimulus/NMR_TOP_DEI90_tb.v"

vsim -L proasic3 -L presynth  -t 1ps presynth.testbench
add wave /testbench/*
run 0
