HelpInfo,D:\Libero_Soc11.9\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,D:\Libero_Soc11.9\SynplifyPro\bin\mbin\assistant
Implementation;Generate Bitstream;RootName:NMR_TOP
Implementation;Compile;RootName:NMR_TOP
Implementation;Compile||(null)||Please refer to the log file for details about 101 Warning(s) , 1 Info(s)||NMR_TOP_compile_log.rpt;liberoaction://open_report/file/NMR_TOP_compile_log.rpt||(null);(null)
Implementation;Place and Route;RootName:NMR_TOP
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Info(s)||NMR_TOP_placeroute_log.rpt;liberoaction://open_report/file/NMR_TOP_placeroute_log.rpt||(null);(null)
